### ISSUE TITLE
Standardize folder structure in all deployment resources repositories

### ISSUE THREAD

**Issue by imesh** [wso2/cloudformation-apim#20]
**Description:**
I think it would be better to use a standard folder structure in all deployment resources repositories. May be something similar to below:

/common/ # files common to all patterns
/pattern-id/ # pattern folder
/pattern-id/confs # pattern configurations folder
/pattern-id/pattern-id-cloud-formation-template.yaml

**Affected Product Version:**
API Manager 2.1.0

**Comment by chirangaalwis** [comment]
@imesh currently, we have Puppet configurations which are used to build the AMIs. They are located separately under AMI configurations, within the project structure. Plus, as suggested in issue https://github.com/wso2/cloudformation-apim/issues/23, it is expected to decouple Puppet from CloudFormation templates.
Thus, are there any other configurations which are expected to be added to the suggested /pattern-id/confs folder?
