### ISSUE TITLE
Decouple Puppet from Cloud Formation templates

### ISSUE THREAD

**Issue by imesh** [wso2/cloudformation-apim#23]
**Description:**
I would like to propose to decouple Puppet from Cloud Formation templates as it may introduce an additional complexity to the deployment and maintenance. A list of parameters can be used for reusing the configuration parameter values without having to declare them multiple times within the CF template. 

In this process if required we can evaluate and see how Puppet support can be provided as a value addition to be used in deployments where Puppet servers are already available.

**Affected Product Version:**
API Manager 2.1.0

**Comment by kasunbg** [comment]
+1 to decouple puppet and cloudformation templates coz cloudformation should be usable against any CM tool. After decoupling, can we document how to use puppet on top of the cloudformation as well?

**Comment by ctienshi** [comment]
We had an internal discussion regarding removing Puppet from CFN templates. This would add an complexity while running an WUM updated pack since, currently the Puppetmaster validates WSO2 credentials and accordingly update the WSO2 product pack and sends to the puppet agents.
