### ISSUE TITLE
Provide Auto-healing and HA for Analytics

### ISSUE THREAD

**Issue by imesh** [wso2/cloudformation-apim#24]
**Description:**
The current CF template uses the IP address of the Analytics instance [1] for publishing API statistics from the API manager nodes. As a result, if the Analytics instance becomes unavailable and get recovered by the autoscaling group, analytics would not work after that point due to IP address being changed. One way of resolving this issue is to use an internal hosted zone with Route 53 and create a domain name for Analytics instances.

In addition, we may need to create two Analytics instances for providing HA with the above approach.

[1] https://github.com/wso2/cloudformation-apim/blob/fdd9ef6f2e32fcda4692449a47d5e136349ee199/default-with-analytics/WSO2AM210-All-In-One-Deployment-VPC.template.yaml#L303

**Affected Product Version:**
API Manager 2.1.0

**Comment by VimukthiPerera** [comment]
Created a new issue to track this in https://github.com/wso2/aws-apim. Therefore can be closed.
https://github.com/wso2/aws-apim/issues/34
