### ISSUE TITLE
Define specific outbound rules in product specific AWS Security Groups

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/cloudformation-apim#25]
**Description:**
Define specific outbound rules in product specific AWS Security Groups. Currently, since no outbound rules are defined, by default the "allow all" rule has been applied.
Thus, it is suggested to move Ubuntu package updates and software installations defined under Launch Configuration user data to AMI creation since, these require connection to the Internet from the private subnets containing product auto scaling groups.

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**
chirangaalwis

**Affected Product Version:**
API Manager 2.1.0

**Comment by VimukthiPerera** [comment]
A new issue has been created in https://github.com/wso2/aws-apim to track this.
https://github.com/wso2/aws-apim/issues/33
