### ISSUE TITLE
Add Amazon CloudWatch Logs

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/cloudformation-apim#26]
**Description:**
Add Amazon CloudWatch Logs support.

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**
chirangaalwis

**Affected Product Version:**
API Manager 2.1.0

**Comment by ctienshi** [comment]
@chirangaalwis 
Since the cost is too high to enable CloudWatch logs, we have decided to publish wso2carbon logs to ElasticSearch. Users could view the logs via Kibana
