### ISSUE TITLE
Folder structure convention for CF repositories

### ISSUE THREAD

**Issue by imesh** [wso2/cloudformation-apim#33]
The purpose of this issue is to formalize the folder structure convention of Cloud Formation (CF) API-M repository and use it as a reference implementation for all other WSO2 CF repositories.

Please find my proposal for the folder structure below:

````bash
/README.md
/images/ # store any images used in the README.md file
/amis/README.md
/amis/apim/README.md
/amis/apim/ # files required for creating API-M AMI
/amis/apim-analytics/README.md
/amis/apim-analytics/ # files required for creating API-M Analytics AMI
/pattern-<number>/README.md
/pattern-<number>/wso2-apim-pattern-1.yaml
/pattern-<number>/images/ # store any images used in the README.md file
````

Appreciate your thoughts on this!

**Comment by VimukthiPerera** [comment]
This folder structure has been followed in https://github.com/wso2/aws-apim. Therefore we can close this.
