### ISSUE TITLE
Server Certificate not found for the key: wsocarbon

### ISSUE THREAD

**Issue by deki** [wso2/cloudformation-apim#39]
**Description:**
Exactly following the steps from README.md will cause the stack creation to fail:

| 08:31:54 UTC+0200 | CREATE_FAILED | AWS::ElasticLoadBalancing::LoadBalancer | WSO2APIMLoadBalancer | Server Certificate not found for the key: arn:aws:iam::0123456789:server-certificate/wsocarbon
| -- | -- | -- | -- | --
| 08:31:54 UTC+0200 | CREATE_FAILED | AWS::ElasticLoadBalancing::LoadBalancer | WSO2APIMAnalyticsLoadBalancer | Server Certificate not found for the key: arn:aws:iam::0123456789:server-certificate/wsocarbon

Looks like this requires a previously uploaded certificate. Should this be done using AWS Certificate manager? This should be listed as a step in README.md.

Have you thought of using https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html within CloudFormation to directly issue a new certificate?

**Affected Product Version:**
master

**OS, DB, other environment details and versions:**    
AWS

**Steps to reproduce:**
Follow instructions from README.md

**Comment by deki** [comment]
In case somebody is looking for a workaround:

1. Extract wso2carbon-public.pem and wso2carbon-priv.pem from repository/resources/security/wso2carbon.jks
2. Upload it using aws cli (see https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_server-certs.html) `aws iam upload-server-certificate --server-certificate-name wso2carbon --certificate-body file://wso2carbon.pem --private-key file://wso2carbon-priv.pem`

**Comment by chamilad** [comment]
@deki We are in the process of fixing this issue. It's both a CF template issue and a README gap. @chirangaalwis  Do we have an issue following the progress?

**Comment by chirangaalwis** [comment]
@deki the same issue has been pointed out within a [pull request](https://github.com/wso2/cloudformation-apim/pull/17#issuecomment-349724881) under this repository.

@deki @chamilad I believe this issue can be used to track the progress of fixing it.

An effort to fix existing issues and fine tune the AWS resources of WSO2 products is underway (as @chamilad has pointed out).

**Comment by ctienshi** [comment]
This issue is fixed in the Readme instructing to upload an SSL certificate in the following new AWS-APIM repository.
https://github.com/wso2/aws-apim/tree/master/pattern-1
